<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class PriceSeederHir extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('prices')->insert([
            [
                'service_code' => 'В01.067.001',
                'service_name' => 'Прием (осмотр, консультация) врача — стоматолога- хирурга первичный',
                'price' => 0,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.067.002',
                'service_name' => 'Прием (осмотр, консультация, составление плана) врача — стоматолога - хирурга повторный',
                'price' => 1500,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.001.002',
                'service_name' => 'Удаление постоянного зуба не сложное',
                'price' => 2000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.001.003',
                'service_name' => 'Удаление постоянного зуба сложное',
                'price' => 4000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.024',
                'service_name' => 'Операция удаления ретинированного, дистопированного или сверхкомплектного зуба',
                'price' => 8000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.007',
                'service_name' => 'Резекция верхушки корня',
                'price' => 8000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.013',
                'service_name' => 'Отсроченный кюретаж лунки удаленного зуба (лечение альвеолита)',
                'price' => 2000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.059',
                'service_name' => 'Гемисекция зуба',
                'price' => 3000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.059.001',
                'service_name' => 'Ампутация корня',
                'price' => 3000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.060',
                'service_name' => 'Коронарно-радикулярная сепарация',
                'price' => 3000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.042',
                'service_name' => 'Пластика уздечки верхней губы',
                'price' => 5000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'A16.07.040',
                'service_name' => 'Лоскутная операция в полости рта (пластика рецессии десны)',
                'price' => 7000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.038',
                'service_name' => 'Открытый кюретаж при заболеваниях парадонта 2-3 з.',
                'price' => 7000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.039',
                'service_name' => 'Закрытый кюретаж при заболеваниях парадонта в области зуба',
                'price' => 2000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.058',
                'service_name' => 'Лечение перикоронита (промывание, рассечение и /или иссечение капюшона)',
                'price' => 3000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А11.03.003.003',
                'service_name' => 'Внутрикостное введение лекарственных препаратов. Введение остеотропных препаратов в виде синтетических гранул (НКР)',
                'price' => 14000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.026',
                'service_name' => 'Гингивэктомия (Операция удлинения коронки зуба)',
                'price' => 5000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.054.002',
                'service_name' => 'Внутрикостная дентальная имплантация',
                'price' => 35000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.054',
                'service_name' => 'Внутрикостная дентальная имплантация одноэтапная',
                'price' => 32000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.089.001',
                'service_name' => 'Гингивопластика. Подсадка слизисто-соединительнотканного трансплантанта',
                'price' => 7000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.089.002',
                'service_name' => 'Установка формирователя',
                'price' => 3000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.055.001',
                'service_name' => 'Закрытый синус – лифтинг с НКР',
                'price' => 35000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.055.002',
                'service_name' => 'Открытый синус – лифтинг с НКР',
                'price' => 40000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А11.07.011.002',
                'service_name' => 'Плазмотерапия для лечения и профилактики осложнений после хирургических вмешательств в полости рта (одна пробирка)',
                'price' => 2000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'TITANIUM_MESH',
                'service_name' => 'Титановая сетка',
                'price' => 10000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'TITANIUM_CAP',
                'service_name' => 'Заглушка титановая',
                'price' => 3000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.014',
                'service_name' => 'Вскрытие и дренирование абсцесса полости рта (Переосттомияомия)',
                'price' => 1000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.041.002',
                'service_name' => 'Коррекция объема и формы альвеолярного отростка. Коррекция альвеолярного гребня для протезирования, остеотомия',
                'price' => 8000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.30.069',
                'service_name' => 'Снятие швов',
                'price' => 0,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'IMPLANT_REMOVAL',
                'service_name' => 'Удаление имплантанта',
                'price' => 8000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А11.03.003.004',
                'service_name' => 'Внутрикостное введение лекарственных препаратов. Введение остеотропных препаратов в виде губок (парасорб)',
                'price' => 2000,
                'section' => 'Хирургическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
