<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

class PriceSeederOrt extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('prices')->insert([
            [
                'service_code' => 'В01.066.001',
                'service_name' => 'Прием (осмотр, консультация) врача — стоматолога- ортопеда первичный',
                'price' => 0,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'В01.066.002',
                'service_name' => 'Прием (осмотр, консультация, составление плана) врача — стоматолога- ортопеда повторный',
                'price' => 1500,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А02.07.006.001',
                'service_name' => 'Определения вида смыкания зубных рядов с помощью лицевой дуги',
                'price' => 6000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А02.07.010',
                'service_name' => 'Исследование на диагностических моделей челюстей',
                'price' => 1000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.053.010',
                'service_name' => 'Снятие несъемной ортопедической конструкции',
                'price' => 1000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А23.07.002.034',
                'service_name' => 'Перебазировка съемного протеза',
                'price' => 3000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А23.07.002.037',
                'service_name' => 'Починка съемного протеза',
                'price' => 3000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А23.07.002.036',
                'service_name' => 'Приварка зуба или кламмера',
                'price' => 1500,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.049',
                'service_name' => 'Повторная фиксация на постоянный цемент несъемных ортопедических конструкций',
                'price' => 2000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.003',
                'service_name' => 'Восстановление зуба вкладкой',
                'price' => 8500,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.001',
                'service_name' => 'Восстановление зуба коронкой пластмассовой временной',
                'price' => 2000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.002',
                'service_name' => 'Восстановление зуба коронкой временной  фрезерованной',
                'price' => 4000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.003',
                'service_name' => 'Восстановление зуба коронкой  цельнолитой',
                'price' => 9000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.004',
                'service_name' => 'Восстановление зуба коронкой металлокерамической',
                'price' => 10500,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.005',
                'service_name' => 'Восстановление зуба коронкой диоксид циркония, покрытые Emax',
                'price' => 25000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.006',
                'service_name' => 'Восстановление зуба коронкой Emax',
                'price' => 25000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.004.007',
                'service_name' => 'Восстановление зуба коронкой Prettau',
                'price' => 18000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.004',
                'service_name' => 'Протезирование зуба металлокерамической коронкой с использованием имплантанта',
                'price' => 27000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.002',
                'service_name' => 'Протезирование зуба коронкой из диоксида циркония с нанесением Emax c использованием имплантанта',
                'price' => 30000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.001',
                'service_name' => 'Протезирование зуба коронкой Prettau с использованием имплантанта',
                'price' => 30000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.003',
                'service_name' => 'Протезирование зуба коронкой Emax с использованием имплантанта',
                'price' => 30000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А6.07.006.006',
                'service_name' => 'Индивидуальный абатмент',
                'price' => 8000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.093.001',
                'service_name' => 'Фиксация внутриканального штифта - литая культевая вкладка',
                'price' => 4000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.006.005',
                'service_name' => 'Протезирование зуба временной коронкой на временном абатменте с использованием имплантанта',
                'price' => 13000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.035.001',
                'service_name' => 'Протезирование частичными съемными пластинчатыми протезами',
                'price' => 20000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.035.002',
                'service_name' => 'Протезирование частичными съемными пластинчатыми протезами, косметическая пластинка',
                'price' => 8000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.023',
                'service_name' => 'Протезирование зубов полными съемными пластинчатыми протезами с индивидуальной ложкой',
                'price' => 20000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.036.001',
                'service_name' => 'Протезирование съемными бюгельными протезами на двух замках',
                'price' => 60000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.036.002',
                'service_name' => 'Протезирование съемными бюгельными протезами на опорно — удерживающих кламмерах',
                'price' => 45000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.036.003',
                'service_name' => 'Дополнительный замок для бюгельного протеза',
                'price' => 7000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.036.004',
                'service_name' => 'Замена матриц в бюгельном протезе',
                'price' => 3000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'service_code' => 'А16.07.021',
                'service_name' => 'Коррекция прикуса с использованием съемных и несъемных ортопедических конструкций - каппа',
                'price' => 4000,
                'section' => 'Ортопедическая стоматология',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

    }
}
